### ISSUE TITLE
Unable to load on production with webpack 2

### ISSUE THREAD

**Issue by emacsuser123** [rxaviers/globalize-webpack-plugin#39] opened 2017-02-17 12:26 UTC
Hi.

I'm using globalize-webpack-plugin with webpack v2, and I'm unable to make my app work properly.
If I use the plugin with "production: false", then the app is loaded successfully, without any problem.
But when I use "production: true", then there is an error like the following: 

> TypeError: e[t] is undefined
 
My production webpack config file looks like the following:

>  ....
> module.exports = {
>     entry: {
>       app: ./app/app.js,
>       vendor: [
>         'globalize',
>         'globalize/dist/globalize-runtime/number',
>         'globalize/dist/globalize-runtime/currency',
>         'globalize/dist/globalize-runtime/date',
>         'globalize/dist/globalize-runtime/message',
>         'globalize/dist/globalize-runtime/plural',
>         'globalize/dist/globalize-runtime/relative-time',
>         'globalize/dist/globalize-runtime/unit'
>       ]
>   },
> ......
>   plugins: [
>     new ExtractTextPlugin({
>       filename: '[name].[hash].css',
>       allChunks: true,
>     }),
>     new webpack.DefinePlugin({
>       'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
>     }),
>     new GlobalizePlugin({
>         production: true,
>         developmentLocale: 'en',
>         supportedLocales: [ 'en' ],
> 	output: 'i18n/[locale].[hash].js'
>     }),
>     new webpack.optimize.CommonsChunkPlugin({
>       name: 'vendor',
>       filename: 'vendor.[hash].js',
>     }),
>     new webpack.optimize.UglifyJsPlugin({
>       mangle: true,
>       beautify: false,
>       dead_code: true
>     }),
>     new HtmlWebpackPlugin({
>       template: __dirname + '/app/index.tmpl.html',
>       filename: 'index.html',
>       inject: 'body'
>     })
>   ]
> 

My package.json file has this build script:

> ....
>     "build": "NODE_ENV=production NODE_LOGGING=false webpack -p --config ./webpack.production.config.js --progress",
> .......

The index.tmpl.html file used has the following content:

> .....
>   <body>
>     <div id="app"></div>
>   </body>
> ....

When I run "npm run build", I can see that the final index.html file created looks like the following:

.......
  <body>
  <div id="app"></div>
  <script type="text/javascript" src="vendor.8f2144886f5a86a70bb1.js"></script><script type="text/javascript" src="app.bundle.8f2144886f5a86a70bb1.js"></script><script type="text/javascript" src="i18n/en.8f2144886f5a86a70bb1.js"></script>
</body>

.........

On my app.js, I have:

> const Globalize = require('globalize');

I assume I do not have to do Globalize.load (....) since this will be done by the globalize-webpack-plugin automatically, based on input parameters for the plugin (production, developmentLocale, supportedLocales). In fact, when I use production: false in the plugin, everything goes ok.

I'm sure I'm missing something, but I do not know what it is.

Is there anything I'm misunderstanding here?

Thanks a lot.
-Bob V

**Comment by rxaviers** [comment] 2017-02-19 12:57
Duplicate of #38, please advise if it's not and I reopen it.

**Closed by rxaviers** 2017-02-19 12:57 UTC

**Comment by emacsuser123** [comment] 2017-02-20 08:33
Hi.
I'm not sure whether it is a duplicate of #38 or not.
Issue #38 talks about only one language .js file being generated (the one defined as development locale).
Of course that could be a problem. Right now, I'm only using one language in the supported locale option, so I think I could live by now with that restriction.
Please note that I only have problems when I set production: true in the plugin. It seems that the generated language .js file does not contain all required functionality when configuration points to production.
Thanks a lot.
-Bob V

**Comment by ieow** [comment] 2017-03-29 08:28
Hitting similar issue.
got browser error below when set production to true
app.js:20 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (app.js:20)
    at eval (eval at <anonymous> (app.js:2207), <anonymous>:46:17)
    at Object.<anonymous> (app.js:2207)

However if production set to false, only developmentLocale is build.
Any workaround?

**Comment by rxaviers** [comment] 2017-03-29 11:31
I would be happy to reopen this issue if we have a better analysis. Ideally we should have a reduced reproducible example. Thanks!!

**Comment by emacsuser123** [comment] 2017-03-29 11:57
Hi.
I did not try to provide a reduced reproducible example because I was
expecting the fix for issue #38 to be available, and then test #39, as you
suggested.

Any plans on a fix for issue #38?

thanks a lot.


2017-03-29 13:31 GMT+02:00 Rafael Xavier de Souza <notifications@github.com>
:

**Comment by rxaviers** [comment] 2017-03-29 12:17
Ok.

> Any plans on a fix for issue #38?

I haven't seen a PR so far. Feel free to submit one. I can provide assistance. Thanks!

**Comment by emacsuser123** [comment] 2017-03-29 12:21
It is my understanding that @nikoskalogridis, the submitter of issue #38,
would do that.

2017-03-29 14:17 GMT+02:00 Rafael Xavier de Souza <notifications@github.com>
:

**Comment by ieow** [comment] 2017-03-29 13:42
I do not know how to reproduce the error,
But i tried the app-npm-webpack example by adding a code line to app/index.js

var Globalize = require( "globalize" );
var startTime = new Date();
Globalize.locale('es')   //--> code added 

When the code is added, the build or start script would make the site prompt some error in the browser.
although it is not the same error i hit, may be you can take a look at that first?

Thanks

**Comment by rxaviers** [comment] 2017-03-29 16:49
> It is my understanding that @nikoskalogridis, the submitter of issue #38, would do that. 

Like I said, I haven't seen a PR so far, therefore feel free to take it over if you have time.

**Comment by rxaviers** [comment] 2017-03-29 16:50
> Globalize.locale('es') //--> code added

@ieow, using globalize-webpack-plugin you don't need (actually, you can't) set locale yourself. Instead, use the plugin options, e.g., `options.developmentLocale`.

**Comment by ieow** [comment] 2017-03-30 05:59
@rxaviers , does that mean that we cant dynamically change the locale ?

**Comment by rxaviers** [comment] 2017-03-30 11:51
> @rxaviers , does that mean that we cant dynamically change the locale ?

Not using this webpack plugin as is. This plugin is opinionated with respect to assuming the application wants a locale at a time, which has to do with this https://github.com/rxaviers/globalize-webpack-plugin/#restrictions.

If you want to load any locale on runtime dynamically, you can simply use globalize as is (and take care of loading the data); OR you can use [globalize-compiler](https://github.com/globalizejs/globalize-compiler#README) and customize it according to your needs.

**Comment by rxaviers** [comment] 2017-04-13 19:35
Please, check if this is fixed by `v0.3.11`. If it's not, post comments and I will reopen it. Thanks!

**Comment by emacsuser123** [comment] 2017-04-16 16:03
Hello.

Now I'm facing a new problem when issuing the "npm run build" command:

`Error: No formatters or parsers has been provided`

I've seen other users are facing the same problem.

These are the package versions I'm using:

globalize: 1.2.3
cldr-data: 31.0.2
globalize-webpack-plugin: 0.3.12
webpack: 2.4.1

**Comment by djflex68** [comment] 2017-08-28 21:17
@rxaviers
If I correctly understand your answer, this means that even on production mode, there isn't any way using the webpack Plugin to dynamically change the language at runtime ?
The user of my app should be able to switch the language at Runtime, so in this case I would have to include globalize/cldr-data files myself if I'm right ?
Thanks for confirming !

**Comment by rxaviers** [comment] 2017-08-29 09:31
@djflex68 your understanding is correct, the goal with this webpack plugin was to support one language at a time; but I suspect that you can load chunks for the languages you need simultaneous support and then use `Globalize.locale` to change languages (among the ones you load). That needs test,

**Comment by diligiant** [comment] 2017-08-29 09:48
Since https://github.com/rxaviers/globalize-webpack-plugin/pull/65, the language files don't overlap and therefore you can manipulate many of them simultaneously.

**Comment by rxaviers** [comment] 2017-08-29 10:53
Thank you @diligiant
